Repository pubky/pubky-nexus, pull requests merged in 2024-11, with the labels that each got.

#176 Add pubky.app models specs
  pubky.app_specs.md
Labels: 🔮 nexus

#174 feat: Add timeline param to request streams
  benches/search.rs
  docker/db-graph/mocks/files.cypher
  docker/db-graph/mocks/mutes.cypher
  docker/db-graph/mocks/posts.cypher
  docker/db-graph/mocks/tags.cypher
  docker/db-graph/skunk.cypher
  src/db/graph/queries/get.rs
  src/models/post/stream.rs
  src/models/tag/search.rs
  src/routes/v0/search/tags.rs
  src/routes/v0/stream/posts.rs
  tests/service/all.rs
  tests/service/stream/bookmarks.rs
  tests/service/stream/mod.rs
  tests/service/stream/posts.rs
  tests/service/stream/reach.rs
  tests/service/stream/reach/engagement.rs
  tests/service/stream/reach/mod.rs
  tests/service/stream/reach/timeline.rs
  tests/service/stream/reach/utils.rs
  tests/service/stream/tags.rs
  tests/service/stream/utils.rs
  tests/service/stream/w_multiple_filters.rs
  tests/service/stream/w_tags.rs
  tests/watcher/bookmarks/del.rs
  tests/watcher/bookmarks/raw.rs
  tests/watcher/bookmarks/viewer.rs
Labels: enhancement, 🔮 nexus, 🌐 service

#183 Fix: alternative StreamSource. Maybe doable?
  benches/search.rs
  benches/streams_benches/bookmarks.rs
  benches/streams_benches/reach.rs
  benches/streams_benches/sorting.rs
  benches/streams_benches/tag.rs
  benches/streams_benches/utils.rs
  benches/tag.rs
  benches/thread.rs
  src/db/graph/queries/get.rs
  src/models/post/mod.rs
  src/models/post/stream.rs
  src/routes/v0/stream/mod.rs
  src/routes/v0/stream/posts.rs
  src/routes/v0/stream/queries.rs
  src/types/mod.rs
  tests/service/stream/bookmarks.rs
  tests/service/stream/reach/timeline.rs
  tests/service/stream/replies.rs
  tests/service/stream/user.rs
Labels: 🔮 nexus, refactor, 🌐 service

#189 Update readme
  README.md
Labels: documentation, enhancement

#191 Add specs for feeds and least_read
  pubky.app_specs.md
Labels: enhancement

#192 Fix(watcher): panics on multibyte characters cutoffs
  src/models/pubky_app/post.rs
  src/models/pubky_app/tag.rs
  src/models/pubky_app/user.rs
Labels: bug, 🔮 nexus, 👀 watcher

#151 fix(watcher): accept any embed, post kind to lowercase
  docker/db-graph/mocks/posts.cypher
  docker/db-graph/mocks/tags.cypher
  docker/db-graph/skunk.cypher
  src/db/graph/queries/put.rs
  src/events/handlers/post.rs
  src/models/pubky_app/post.rs
Labels: bug

#220 Chore(service): cleanup unused api and group swagger-ui
  Cargo.toml
  benches/thread.rs
  src/db/graph/queries/get.rs
  src/models/post/mod.rs
  src/routes/v0/file/details.rs
  src/routes/v0/file/list.rs
  src/routes/v0/info.rs
  src/routes/v0/notification/list.rs
  src/routes/v0/post/bookmark.rs
  src/routes/v0/post/counts.rs
  src/routes/v0/post/details.rs
  src/routes/v0/post/mod.rs
  src/routes/v0/post/tags.rs
  src/routes/v0/post/thread.rs
  src/routes/v0/post/view.rs
  src/routes/v0/search/tags.rs
  src/routes/v0/search/users.rs
  src/routes/v0/stream/posts.rs
  src/routes/v0/stream/users.rs
  src/routes/v0/tag/global.rs
  src/routes/v0/user/counts.rs
  src/routes/v0/user/details.rs
  src/routes/v0/user/follows.rs
  src/routes/v0/user/muted.rs
  src/routes/v0/user/relationship.rs
  src/routes/v0/user/tags.rs
  src/routes/v0/user/view.rs
  tests/service/all.rs
  tests/watcher/posts/reply.rs
Labels: 🔮 nexus, chores, 🌐 service

#217 Feat(service): add stream of recommended users
  src/db/graph/queries/get.rs
  src/db/kv/index/sets.rs
  src/db/kv/traits.rs
  src/models/follow/traits.rs
  src/models/tag/stream.rs
  src/models/tag/traits/collection.rs
  src/models/user/muted.rs
  src/models/user/stream.rs
  src/routes/v0/stream/users.rs
  tests/service/all.rs
  tests/service/stream/mod.rs
  tests/service/stream/users.rs
Labels: enhancement, 🔮 nexus, 🌐 service

#224 Fix(service): avoid self on recommended users
  src/db/graph/queries/get.rs
Labels: bug, 🔮 nexus, 🌐 service

#229 fix(docs): swagger docs
  src/routes/v0/file/list.rs
  src/routes/v0/notification/list.rs
  src/routes/v0/post/tags.rs
  src/routes/v0/stream/users.rs
  src/routes/v0/tag/global.rs
Labels: bug, documentation, 🔮 nexus
