Repository pubky/pubky-nexus, pull requests merged in 2025-03, with the labels that each got.

#393 feat(api): add response compression with tower‑http
  Cargo.lock
  nexus-api/Cargo.toml
  nexus-api/src/routes/mod.rs
  nexus-api/tests/stream/post/posts.rs
  nexus-api/tests/stream/user/influencers.rs
  nexus-api/tests/stream/user/list.rs
  nexus-api/tests/stream/user/score.rs
  nexus-api/tests/tags/post.rs
  nexus-api/tests/tags/search.rs
  nexus-api/tests/tags/user.rs
  nexus-api/tests/tags/wot.rs
  nexus-api/tests/user/reach.rs
  nexus-api/tests/user/search.rs
  nexus-api/tests/user/views.rs
  nexus-api/tests/utils/mod.rs
Labels: enhancement, 🌐 service

#399 chore: workflow broken mirror
  .github/workflows/test.yml
Labels: dependencies

#395 bug: fix active users cypher query
  docker/test-graph/mocks/hot-tags.cypher
  nexus-api/tests/stream/user/influencers.rs
  nexus-api/tests/tags/hot.rs
  nexus-common/src/db/graph/queries/get.rs
Labels: bug

#403 bug: add a custom limit for user reach in post streams
  nexus-common/src/models/post/stream.rs
Labels: bug

#404 fix: running timeframe hot tags
  nexus-common/src/types/timeframe.rs
Labels: bug, 🔮 nexus
