Repository pubky/pubky-nexus, pull requests merged in 2025-09, with the labels that each got.

#568 Fix `Homeserver::get_all_from_graph()`: throw error on empty list
  nexus-common/src/models/homeserver.rs
Labels: 🪡 chores

#573 feat: ingest hs from tag and follow events
  nexus-watcher/src/events/handlers/follow.rs
  nexus-watcher/src/events/handlers/post.rs
  nexus-watcher/src/events/handlers/tag.rs
  nexus-watcher/src/service/homeserver.rs
  nexus-watcher/src/service/mod.rs
  nexus-watcher/tests/event_processor/homeserver/ingest_homeservers_from_follow_events.rs
  nexus-watcher/tests/event_processor/homeserver/ingest_homeservers_from_post_events.rs
  nexus-watcher/tests/event_processor/homeserver/ingest_homeservers_from_tag_events.rs
  nexus-watcher/tests/event_processor/homeserver/mod.rs
  nexus-watcher/tests/event_processor/homeserver/utils.rs
  nexus-watcher/tests/service/event_processing_multiple_homeservers.rs
  nexus-watcher/tests/service/mock_event_processor.rs
  nexus-watcher/tests/service/mod.rs
  nexus-watcher/tests/service/utils/mod.rs
  nexus-watcher/tests/service/utils/processor.rs
Labels: 👀 watcher, 🕸️ decentralization

#576 Correctly handle and track panicks in event processor runs
  nexus-watcher/src/service/constants.rs
  nexus-watcher/src/service/processor.rs
  nexus-watcher/src/service/processor_factory.rs
  nexus-watcher/src/service/traits/tevent_processor.rs
  nexus-watcher/src/service/traits/tevent_processor_factory.rs
  nexus-watcher/tests/event_processor/network/counts.rs
  nexus-watcher/tests/event_processor/tags/fail_index.rs
  nexus-watcher/tests/service/event_processing_multiple_homeservers.rs
  nexus-watcher/tests/service/event_processor_prioritization.rs
  nexus-watcher/tests/service/mock_event_processor.rs
  nexus-watcher/tests/service/signal.rs
  nexus-watcher/tests/service/utils/processor.rs
  nexus-watcher/tests/service/utils/processor_factory.rs
Labels: 🐞 bug, 🪡 chores
