Repository pubky/pubky-nexus, pull requests merged in 2025-01, with the labels that each got.

#274 chore: derive Default trait
  src/models/post/stream.rs
  src/models/user/tags.rs
Labels: 🔮 nexus, chores

#253 feat: add graph return control for all ingestion events
  Cargo.lock
  Cargo.toml
  src/db/graph/exec.rs
  src/db/graph/queries/del.rs
  src/db/graph/queries/get.rs
  src/db/graph/queries/put.rs
  src/db/kv/traits.rs
  src/events/handlers/bookmark.rs
  src/events/handlers/file.rs
  src/events/handlers/follow.rs
  src/events/handlers/mute.rs
  src/events/handlers/post.rs
  src/events/handlers/tag.rs
  src/events/handlers/user.rs
  src/events/mod.rs
  src/events/processor.rs
  src/lib.rs
  src/models/file/details.rs
  src/models/follow/followers.rs
  src/models/follow/following.rs
  src/models/follow/traits.rs
  src/models/post/bookmark.rs
  src/models/post/details.rs
  src/models/post/relationships.rs
  src/models/tag/post.rs
  src/models/tag/stream.rs
  src/models/tag/traits/collection.rs
  src/models/tag/traits/taggers.rs
  src/models/tag/user.rs
  src/models/traits.rs
  src/models/user/details.rs
  src/models/user/follows.rs
  src/models/user/muted.rs
  src/routes/macros.rs
  src/routes/v0/file/mod.rs
  src/routes/v0/notification/mod.rs
  src/routes/v0/post/mod.rs
  src/routes/v0/search/mod.rs
  src/routes/v0/tag/mod.rs
  src/routes/v0/user/mod.rs
  tests/watcher/bookmarks/fail_index.rs
  tests/watcher/bookmarks/mod.rs
  tests/watcher/follows/fail_index.rs
  tests/watcher/follows/mod.rs
  tests/watcher/mutes/fail_index.rs
  tests/watcher/mutes/mod.rs
  tests/watcher/posts/fail_reply.rs
  tests/watcher/posts/fail_repost.rs
  tests/watcher/posts/fail_user.rs
  tests/watcher/posts/mod.rs
  tests/watcher/tags/fail_index.rs
  tests/watcher/tags/mod.rs
  tests/watcher/utils/watcher.rs
Labels: enhancement, 🔮 nexus, 👀 watcher

#275 fix hot tags tests failing based on time of the month
  docker/db-graph/mocks/hot-tags.cypher
  tests/service/tags/hot.rs
Labels: 🔮 nexus, chores

#277 Chore: bump pubky v0.4, pkarr v3, mainline v5
  .env-sample
  Cargo.lock
  Cargo.toml
  benches/watcher.rs
  examples/new_homeserver_user.rs
  examples/stress_network_sim.rs
  src/config.rs
  src/db/connectors/pubky.rs
  src/events/handlers/bookmark.rs
  src/events/handlers/file.rs
  src/events/handlers/follow.rs
  src/events/handlers/mute.rs
  src/events/handlers/post.rs
  src/events/handlers/tag.rs
  src/events/handlers/user.rs
  src/events/mod.rs
  src/events/processor.rs
  src/models/homeserver.rs
  tests/watcher/bookmarks/del.rs
  tests/watcher/bookmarks/raw.rs
  tests/watcher/bookmarks/viewer.rs
  tests/watcher/files/create.rs
  tests/watcher/files/delete.rs
  tests/watcher/network/counts.rs
  tests/watcher/posts/attachments.rs
  tests/watcher/posts/del_bookmarked_notification.rs
  tests/watcher/posts/del_tagged_notification.rs
  tests/watcher/posts/del_with_relations.rs
  tests/watcher/posts/edit_bookmarked_notification.rs
  tests/watcher/posts/edit_reply_parent_notification.rs
  tests/watcher/posts/edit_reposted_notification.rs
  tests/watcher/posts/edit_tagged_notification.rs
  tests/watcher/posts/reply_engagement.rs
  tests/watcher/tags/post_del.rs
  tests/watcher/tags/post_muti_user.rs
  tests/watcher/tags/post_notification.rs
  tests/watcher/tags/post_put.rs
  tests/watcher/tags/user_notification.rs
  tests/watcher/tags/user_to_self_put.rs
  tests/watcher/tags/user_to_user_del.rs
  tests/watcher/tags/user_to_user_put.rs
  tests/watcher/users/del_with_relations.rs
  tests/watcher/utils/dht.rs
  tests/watcher/utils/watcher.rs
Labels: enhancement, dependencies, 🔮 nexus, 👀 watcher, chores

#293 feat: add skip pagination over post tags
  benches/tag.rs
  src/models/post/view.rs
  src/models/tag/traits/collection.rs
  src/models/user/view.rs
  src/routes/v0/endpoints.rs
  src/routes/v0/post/tags.rs
  src/routes/v0/post/view.rs
  src/routes/v0/types.rs
  src/routes/v0/user/tags.rs
  tests/service/all.rs
  tests/service/mod.rs
  tests/service/post/mod.rs
  tests/service/post/view.rs
  tests/service/tags/post.rs
  tests/service/tags/user.rs
  tests/service/tags/wot.rs
  tests/watcher/tags/post_del.rs
  tests/watcher/tags/post_muti_user.rs
  tests/watcher/tags/post_put.rs
  tests/watcher/tags/user_to_self_put.rs
  tests/watcher/tags/user_to_user_del.rs
  tests/watcher/tags/user_to_user_put.rs
Labels: enhancement, 🔮 nexus, 🌐 service

#299 chore: move create use example to specs crate
  examples/new_homeserver_user.rs
Labels: documentation, 🔮 nexus, chores

#260 Fix: user search duplicate bug
  src/db/kv/index/json.rs
  src/models/file/details.rs
  src/models/user/details.rs
  src/models/user/search.rs
Labels: bug, 🔮 nexus, 👀 watcher
