Repository pubky/pubky-nexus, pull requests merged in 2025-02, with the labels that each got.

#310 chore: update nexus wireframe
  README.md
  docs/files/pubky-nexus.tldr
Labels: chores

#309 fix: empty tags param bug on post stream endpoint
  src/routes/v0/stream/posts.rs
  tests/service/stream/post/tags.rs
Labels: chores

#294 chore: refactor hot tags endpoint
  benches/tag.rs
  docker/db-graph/mocks/hot-tags.cypher
  src/db/graph/queries/get.rs
  src/db/kv/traits.rs
  src/events/handlers/tag.rs
  src/lib.rs
  src/models/homeserver.rs
  src/models/post/bookmark.rs
  src/models/post/counts.rs
  src/models/post/details.rs
  src/models/post/relationships.rs
  src/models/tag/global.rs
  src/models/tag/mod.rs
  src/models/tag/search.rs
  src/models/tag/stream.rs
  src/models/tag/traits/collection.rs
  src/models/user/counts.rs
  src/models/user/search.rs
  src/routes/v0/endpoints.rs
  src/routes/v0/tag/global.rs
  src/routes/v0/tag/mod.rs
  src/setup.rs
  tests/service/stream/post/posts.rs
  tests/service/tags/hot.rs
  tests/service/tags/wot.rs
  tests/service/utils.rs
  tests/watcher/follows/del_friends.rs
  tests/watcher/follows/del_sequential.rs
  tests/watcher/follows/put_friends.rs
  tests/watcher/follows/put_sequential.rs
  tests/watcher/mentions/raw.rs
  tests/watcher/network/counts.rs
  tests/watcher/posts/del_without_relations.rs
  tests/watcher/posts/reply.rs
  tests/watcher/posts/repost.rs
  tests/watcher/tags/post_del.rs
  tests/watcher/tags/post_muti_user.rs
  tests/watcher/tags/post_put.rs
Labels: 🔮 nexus, chores, 🌐 service

#247 feat: retry manager
  .env-sample
  .github/workflows/test.yml
  Cargo.lock
  benches/watcher.rs
  examples/from_file.rs
  src/db/connectors/pubky.rs
  src/db/graph/exec.rs
  src/db/graph/queries/get.rs
  src/db/graph/queries/put.rs
  src/db/kv/traits.rs
  src/events/error.rs
  src/events/handlers/bookmark.rs
  src/events/handlers/file.rs
  src/events/handlers/follow.rs
  src/events/handlers/mute.rs
  src/events/handlers/post.rs
  src/events/handlers/tag.rs
  src/events/handlers/user.rs
  src/events/mod.rs
  src/events/processor.rs
  src/events/retry/event.rs
  src/events/retry/mod.rs
  src/events/uri.rs
  src/models/post/stream.rs
  src/models/tag/search.rs
  src/models/user/search.rs
  src/routes/v0/stream/posts.rs
  src/watcher.rs
  tests/service/stream/post/reach/utils.rs
  tests/watcher/bookmarks/fail_index.rs
  tests/watcher/bookmarks/mod.rs
  tests/watcher/bookmarks/retry_bookmark.rs
  tests/watcher/follows/mod.rs
  tests/watcher/follows/retry_follow.rs
  tests/watcher/mutes/mod.rs
  tests/watcher/mutes/retry_mute.rs
  tests/watcher/posts/mod.rs
  tests/watcher/posts/retry_all.rs
  tests/watcher/posts/retry_post.rs
  tests/watcher/posts/retry_reply.rs
  tests/watcher/posts/retry_repost.rs
  tests/watcher/posts/utils.rs
  tests/watcher/tags/fail_index.rs
  tests/watcher/tags/mod.rs
  tests/watcher/tags/retry_post_tag.rs
  tests/watcher/tags/retry_user_tag.rs
  tests/watcher/tags/utils.rs
  tests/watcher/users/raw.rs
  tests/watcher/users/utils.rs
  tests/watcher/utils/dht.rs
  tests/watcher/utils/watcher.rs
Labels: enhancement, 🔮 nexus, 👀 watcher

#249 tests: refactor service tests as standalone
  .github/workflows/test.yml
  Cargo.toml
  README.md
  benches/setup.rs
  examples/from_file.rs
  src/lib.rs
  src/mock_db.rs
  src/models/post/details.rs
  src/models/user/details.rs
  src/models/user/search.rs
  src/service.rs
  src/setup.rs
  src/watcher.rs
  tests/mod.rs
  tests/service/all.rs
  tests/service/endpoints.rs
  tests/service/post/view.rs
  tests/service/stream/post/author.rs
  tests/service/stream/post/author_replies.rs
  tests/service/stream/post/bookmarks.rs
  tests/service/stream/post/kind/all.rs
  tests/service/stream/post/kind/file.rs
  tests/service/stream/post/kind/image.rs
  tests/service/stream/post/kind/link.rs
  tests/service/stream/post/kind/long.rs
  tests/service/stream/post/kind/video.rs
  tests/service/stream/post/post_replies.rs
  tests/service/stream/post/posts.rs
  tests/service/stream/post/reach/engagement.rs
  tests/service/stream/post/reach/timeline.rs
  tests/service/stream/post/reach/utils.rs
  tests/service/stream/post/tags.rs
  tests/service/stream/user/list.rs
  tests/service/stream/user/reach.rs
  tests/service/stream/user/score.rs
  tests/service/stream/user/search.rs
  tests/service/tags/hot.rs
  tests/service/tags/mod.rs
  tests/service/tags/post.rs
  tests/service/tags/search.rs
  tests/service/tags/user.rs
  tests/service/tags/wot.rs
  tests/service/user/reach.rs
  tests/service/user/search.rs
  tests/service/user/views.rs
  tests/service/utils.rs
  tests/utils.rs
  tests/watcher/files/create.rs
  tests/watcher/files/delete.rs
  tests/watcher/posts/del_tagged_notification.rs
  tests/watcher/utils/watcher.rs
Labels: 🔮 nexus, refactor, chores

#323 chore: improve poll events error handling
  src/events/processor.rs
Labels: chores

#328 bug: inconsistent indexing
  src/events/handlers/tag.rs
Labels: bug

#327 feat: add relationship boolean in all tags related endpoints
  src/db/kv/index/sets.rs
  src/db/kv/traits.rs
  src/events/handlers/follow.rs
  src/models/tag/details.rs
  src/models/tag/search.rs
  src/models/tag/traits/collection.rs
  src/models/tag/traits/taggers.rs
  src/routes/v0/post/mod.rs
  src/routes/v0/post/tags.rs
  src/routes/v0/user/mod.rs
  src/routes/v0/user/tags.rs
  tests/service/post/view.rs
  tests/service/stream/post/kind/mod.rs
  tests/service/tags/post.rs
  tests/service/tags/user.rs
  tests/service/tags/wot.rs
  tests/service/user/views.rs
  tests/watcher/tags/post_del.rs
  tests/watcher/tags/post_muti_user.rs
  tests/watcher/tags/post_put.rs
  tests/watcher/tags/user_to_self_put.rs
  tests/watcher/tags/user_to_user_del.rs
  tests/watcher/tags/user_to_user_put.rs
Labels: enhancement, 🔮 nexus, 🌐 service

#336 feat: add in user/post counts index the unique tags field
  src/db/graph/queries/get.rs
  src/db/kv/index/json.rs
  src/events/handlers/bookmark.rs
  src/events/handlers/follow.rs
  src/events/handlers/post.rs
  src/events/handlers/tag.rs
  src/events/handlers/user.rs
  src/models/post/counts.rs
  src/models/user/counts.rs
  src/models/user/stream.rs
  tests/service/post/view.rs
  tests/service/user/views.rs
  tests/watcher/network/counts.rs
  tests/watcher/tags/mod.rs
  tests/watcher/tags/multi_user.rs
  tests/watcher/tags/post_del.rs
  tests/watcher/tags/post_multi_user.rs
  tests/watcher/tags/post_put.rs
  tests/watcher/tags/user_to_self_put.rs
  tests/watcher/tags/user_to_user_del.rs
  tests/watcher/tags/user_to_user_put.rs
  tests/watcher/users/raw.rs
Labels: enhancement

#337 chore: user and post counts migration
  src/db/migrations/manager.rs
  src/db/migrations/migrations_list/mod.rs
  src/db/migrations/migrations_list/tag_counts_reset_1739459180.rs
  src/db/migrations/mod.rs
Labels: chores

#338 chore: file event error handling
  src/events/handlers/file.rs
  src/models/file/details.rs
Labels: chores

#357 deps: opentelemetry
  Cargo.lock
  Cargo.toml
  src/setup.rs
Labels: dependencies
